[2023-05-15T00:00:02.593+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-15T00:00:02.600+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2023-05-14T00:00:00+00:00 [queued]>
[2023-05-15T00:00:02.600+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T00:00:02.600+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-15T00:00:02.600+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T00:00:02.609+0000] {taskinstance.py:1309} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-05-14 00:00:00+00:00
[2023-05-15T00:00:02.613+0000] {standard_task_runner.py:55} INFO - Started process 116844 to run task
[2023-05-15T00:00:02.615+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2023-05-14T00:00:00+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpk5ek798y']
[2023-05-15T00:00:02.616+0000] {standard_task_runner.py:83} INFO - Job 446: Subtask is_api_available
[2023-05-15T00:00:02.655+0000] {task_command.py:389} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2023-05-14T00:00:00+00:00 [running]> on host 1f05588790e0
[2023-05-15T00:00:02.704+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-14T00:00:00+00:00
[2023-05-15T00:00:02.707+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:00:02.712+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:00:03.188+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:00:03.189+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:01:03.250+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:01:03.255+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:01:04.507+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:01:04.507+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:02:04.568+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:02:04.573+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:02:05.254+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:02:05.254+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:03:05.314+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:03:05.319+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:03:06.551+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:03:06.551+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:04:06.611+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:04:06.616+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:04:07.099+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:04:07.099+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:05:07.146+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:05:07.151+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:05:07.633+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:05:07.633+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:06:07.694+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:06:07.699+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:06:08.174+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:06:08.174+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:07:08.229+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:07:08.234+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:07:08.718+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:07:08.718+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:08:08.772+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:08:08.777+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:08:09.257+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:08:09.257+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:09:09.318+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:09:09.324+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:09:09.901+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:09:09.901+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:10:09.960+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:10:09.965+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:10:10.447+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:10:10.447+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:11:10.507+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:11:10.512+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:11:10.995+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:11:10.995+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:12:11.054+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:12:11.070+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:12:11.538+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:12:11.538+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:13:11.598+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:13:11.603+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:13:12.097+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:13:12.097+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:14:12.158+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:14:12.182+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:14:12.670+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:14:12.670+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:15:12.703+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:15:12.708+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:15:13.180+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:15:13.180+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:16:13.238+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:16:13.243+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:16:13.713+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:16:13.713+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:17:13.774+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:17:13.780+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:17:15.083+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:17:15.083+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:18:15.145+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:18:15.149+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:18:15.635+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:18:15.636+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:19:15.694+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:19:15.699+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:19:16.195+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:19:16.195+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:20:16.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:20:16.227+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:20:16.721+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:20:16.721+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:21:16.782+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:21:16.787+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:21:17.258+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:21:17.259+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:22:17.316+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:22:17.321+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:22:17.814+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:22:17.815+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:23:17.876+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:23:17.881+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:23:18.392+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:23:18.392+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:24:18.450+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:24:18.455+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:24:18.958+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:24:18.958+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:25:19.018+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:25:19.023+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:25:19.525+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:25:19.525+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:26:19.565+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:26:19.570+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:26:20.828+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:26:20.828+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:27:20.886+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:27:20.891+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:27:21.380+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:27:21.381+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:28:21.442+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:28:21.447+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:28:21.942+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:28:21.942+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:29:22.002+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:29:22.007+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:29:22.478+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:29:22.478+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:30:22.538+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:30:22.543+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:30:23.017+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:30:23.018+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:31:23.078+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:31:23.084+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:31:24.366+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:31:24.367+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:32:24.427+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:32:24.432+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:32:24.924+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:32:24.924+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:33:24.985+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:33:24.989+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:33:26.204+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:33:26.204+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:34:26.262+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:34:26.267+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:34:26.752+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:34:26.752+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:35:26.810+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:35:26.815+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:35:27.287+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:35:27.287+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:36:27.346+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:36:27.351+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:36:28.594+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:36:28.594+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:37:28.654+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:37:28.659+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:37:29.135+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:37:29.136+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:38:29.194+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:38:29.199+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:38:29.676+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:38:29.677+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:39:29.734+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:39:29.740+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:39:30.230+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:39:30.230+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:40:30.290+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:40:30.295+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:40:30.779+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:40:30.779+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:41:30.838+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:41:30.843+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:41:31.333+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:41:31.333+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:42:31.394+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:42:31.400+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:42:31.878+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:42:31.878+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:43:31.938+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:43:31.942+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:43:32.419+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:43:32.419+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:44:32.480+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:44:32.485+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:44:32.968+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:44:32.969+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:45:33.006+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:45:33.010+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:45:33.504+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:45:33.505+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:46:33.561+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:46:33.565+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:46:34.784+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:46:34.784+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:47:34.842+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:47:34.847+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:47:36.053+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:47:36.053+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:48:36.114+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:48:36.119+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:48:36.757+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:48:36.757+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:49:36.817+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:49:36.827+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:49:38.037+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:49:38.037+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:50:38.085+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:50:38.089+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:50:38.559+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:50:38.559+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:51:38.614+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:51:38.619+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:51:39.096+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:51:39.097+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:52:39.154+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:52:39.159+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:52:40.353+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:52:40.353+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:53:40.414+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:53:40.419+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:53:40.898+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:53:40.898+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:54:40.955+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:54:40.961+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:54:41.455+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:54:41.455+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:55:41.514+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:55:41.519+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:55:41.995+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:55:41.995+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:56:42.051+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:56:42.057+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:56:42.531+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:56:42.531+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:57:42.594+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:57:42.599+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:57:43.859+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:57:43.860+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:58:43.908+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:58:43.913+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:58:44.389+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:58:44.389+0000] {http.py:171} ERROR - Not Found
[2023-05-15T00:59:44.450+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T00:59:44.454+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T00:59:44.927+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T00:59:44.927+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:00:44.981+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:00:44.986+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:00:45.475+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:00:45.476+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:01:45.534+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:01:45.539+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:01:46.040+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:01:46.040+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:02:46.098+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:02:46.122+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:02:46.631+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:02:46.631+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:03:46.680+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:03:46.685+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:03:47.175+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:03:47.175+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:04:47.236+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:04:47.241+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:04:47.733+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:04:47.734+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:05:47.794+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:05:47.799+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:05:48.281+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:05:48.281+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:06:48.342+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:06:48.347+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:06:48.828+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:06:48.829+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:07:48.886+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:07:48.891+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:07:50.113+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:07:50.113+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:08:50.164+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:08:50.169+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:08:50.643+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:08:50.643+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:09:50.702+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:09:50.710+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:09:51.201+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:09:51.201+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:10:51.262+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:10:51.267+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:10:52.515+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:10:52.515+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:11:52.574+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:11:52.580+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:11:53.063+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:11:53.063+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:12:53.122+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:12:53.142+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:12:53.617+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:12:53.618+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:13:53.679+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:13:53.684+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:13:54.895+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:13:54.895+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:14:54.954+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:14:54.959+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:14:55.443+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:14:55.444+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:15:55.502+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:15:55.508+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:15:56.003+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:15:56.003+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:16:56.062+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:16:56.067+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:16:56.539+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:16:56.539+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:17:56.578+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:17:56.584+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:17:57.844+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:17:57.845+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:18:57.906+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:18:57.911+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:18:58.413+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:18:58.413+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:19:58.474+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:19:58.479+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:19:58.970+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:19:58.970+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:20:59.031+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:20:59.036+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:20:59.585+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:20:59.586+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:21:59.647+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:21:59.652+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:22:00.133+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:22:00.133+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:23:00.186+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:23:00.191+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:23:00.685+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:23:00.686+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:24:00.746+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:24:00.751+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:24:01.244+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:24:01.244+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:25:01.305+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:25:01.309+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:25:01.782+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:25:01.782+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:26:01.842+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:26:01.847+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:26:02.314+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:26:02.314+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:27:02.374+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:27:02.379+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:27:02.867+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:27:02.867+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:28:02.927+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:28:02.932+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:28:03.405+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:28:03.405+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:29:03.466+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:29:03.471+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:29:03.957+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:29:03.957+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:30:04.018+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:30:04.023+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:30:05.324+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:30:05.324+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:31:05.385+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:31:05.390+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:31:05.861+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:31:05.861+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:32:05.914+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:32:05.919+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:32:06.398+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:32:06.399+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:33:06.459+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:33:06.464+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:33:06.946+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:33:06.947+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:34:07.007+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:34:07.012+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:34:07.501+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:34:07.501+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:35:07.562+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:35:07.567+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:35:08.040+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:35:08.041+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:36:08.102+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:36:08.108+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:36:08.596+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:36:08.596+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:37:08.654+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:37:08.659+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:37:09.149+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:37:09.149+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:38:09.204+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:38:09.209+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:38:09.673+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:38:09.674+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:39:09.734+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:39:09.742+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:39:10.216+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:39:10.216+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:40:10.274+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:40:10.281+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:40:10.750+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:40:10.750+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:41:10.810+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:41:10.816+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:41:11.282+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:41:11.283+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:42:11.342+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:42:11.347+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:42:12.541+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:42:12.541+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:43:12.602+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:43:12.607+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:43:13.125+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:43:13.125+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:44:13.186+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:44:13.191+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:44:13.658+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:44:13.658+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:45:13.718+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:45:13.724+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:45:14.202+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:45:14.203+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:46:14.208+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:46:14.214+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:46:14.681+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:46:14.681+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:47:14.742+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:47:14.747+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:47:15.215+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:47:15.215+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:48:15.276+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:48:15.281+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:48:15.748+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:48:15.748+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:49:15.773+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:49:15.778+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:49:16.265+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:49:16.265+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:50:16.325+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:50:16.330+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:50:16.805+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:50:16.805+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:51:16.866+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:51:16.871+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:51:17.340+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:51:17.340+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:52:17.398+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:52:17.403+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:52:17.881+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:52:17.881+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:53:17.942+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:53:17.949+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:53:18.432+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:53:18.432+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:54:18.482+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:54:18.488+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:54:18.980+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:54:18.981+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:55:19.042+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:55:19.048+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:55:19.538+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:55:19.538+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:56:19.599+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:56:19.603+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:56:20.850+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:56:20.850+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:57:20.910+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:57:20.915+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:57:22.111+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:57:22.112+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:58:22.170+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:58:22.175+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:58:22.652+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:58:22.653+0000] {http.py:171} ERROR - Not Found
[2023-05-15T01:59:22.687+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T01:59:22.693+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T01:59:23.178+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T01:59:23.178+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:00:23.238+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:00:23.243+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:00:23.712+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:00:23.712+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:01:23.770+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:01:23.776+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:01:24.260+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:01:24.260+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:02:24.318+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:02:24.354+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:02:24.843+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:02:24.843+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:03:24.893+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:03:24.897+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:03:26.103+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:03:26.104+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:04:26.153+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:04:26.157+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:04:27.513+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:04:27.514+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:05:27.574+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:05:27.579+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:05:28.793+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:05:28.793+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:06:28.854+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:06:28.859+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:06:29.336+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:06:29.336+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:07:29.377+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:07:29.381+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:07:29.869+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:07:29.869+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:08:29.922+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:08:29.927+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:08:30.416+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:08:30.417+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:09:30.477+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:09:30.483+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:09:30.967+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:09:30.967+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:10:31.026+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:10:31.031+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:10:31.517+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:10:31.517+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:11:31.578+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:11:31.589+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:11:32.078+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:11:32.079+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:12:32.138+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:12:32.143+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:12:32.632+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:12:32.632+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:13:32.690+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:13:32.695+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:13:33.168+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:13:33.168+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:14:33.226+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:14:33.232+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:14:33.712+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:14:33.712+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:15:33.770+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:15:33.782+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:15:34.263+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:15:34.263+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:16:34.322+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:16:34.327+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:16:34.813+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:16:34.813+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:17:34.874+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:17:34.878+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:17:35.360+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:17:35.360+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:18:35.420+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:18:35.425+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:18:35.919+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:18:35.919+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:19:35.978+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:19:35.983+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:19:36.455+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:19:36.456+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:20:36.514+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:20:36.521+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:20:37.009+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:20:37.009+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:21:37.070+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:21:37.075+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:21:37.557+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:21:37.557+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:22:37.618+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:22:37.623+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:22:38.104+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:22:38.104+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:23:38.163+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:23:38.168+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:23:38.644+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:23:38.644+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:24:38.699+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:24:38.705+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:24:39.178+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:24:39.178+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:25:39.237+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:25:39.249+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:25:39.756+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:25:39.756+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:26:39.814+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:26:39.830+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:26:40.300+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:26:40.301+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:27:40.362+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:27:40.367+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:27:40.851+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:27:40.852+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:28:40.910+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:28:40.915+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:28:41.401+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:28:41.401+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:29:41.458+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:29:41.462+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:29:41.966+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:29:41.967+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:30:42.026+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:30:42.031+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:30:42.512+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:30:42.512+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:31:42.570+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:31:42.575+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:31:43.057+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:31:43.057+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:32:43.118+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:32:43.124+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:32:43.607+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:32:43.607+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:33:43.666+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:33:43.672+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:33:44.143+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:33:44.143+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:34:44.200+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:34:44.206+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:34:44.723+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:34:44.723+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:35:44.782+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:35:44.788+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:35:45.291+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:35:45.291+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:36:45.350+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:36:45.355+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:36:46.558+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:36:46.558+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:37:46.618+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:37:46.623+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:37:47.102+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:37:47.102+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:38:47.163+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:38:47.168+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:38:47.639+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:38:47.639+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:39:47.698+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:39:47.703+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:39:48.184+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:39:48.184+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:40:48.246+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:40:48.251+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:40:48.734+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:40:48.735+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:41:48.796+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:41:48.801+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:41:50.008+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:41:50.008+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:42:50.066+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:42:50.071+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:42:51.329+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:42:51.330+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:43:51.391+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:43:51.396+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:43:51.885+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:43:51.885+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:44:51.916+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:44:51.920+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:44:52.413+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:44:52.414+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:45:52.474+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:45:52.479+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:45:52.959+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:45:52.959+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:46:53.018+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:46:53.023+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:46:53.510+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:46:53.511+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:47:53.570+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:47:53.577+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:47:54.048+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:47:54.049+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:48:54.110+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:48:54.116+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:48:54.619+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:48:54.620+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:49:54.678+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:49:54.683+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:49:55.161+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:49:55.161+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:50:55.222+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:50:55.228+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:50:55.701+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:50:55.701+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:51:55.762+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:51:55.768+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:51:56.256+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:51:56.256+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:52:56.314+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:52:56.319+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:52:56.811+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:52:56.811+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:53:56.870+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:53:56.875+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:53:57.361+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:53:57.361+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:54:57.422+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:54:57.430+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:54:57.904+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:54:57.905+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:55:57.966+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:55:57.971+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:55:58.447+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:55:58.447+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:56:58.508+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:56:58.513+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:56:59.804+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:56:59.804+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:57:59.862+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:57:59.868+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:58:00.349+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:58:00.350+0000] {http.py:171} ERROR - Not Found
[2023-05-15T02:59:00.410+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T02:59:00.415+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T02:59:00.915+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T02:59:00.915+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:00:00.976+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:00:00.982+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:00:01.484+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:00:01.484+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:01:01.545+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:01:01.550+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:01:02.025+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:01:02.026+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:02:02.086+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:02:02.091+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:02:02.567+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:02:02.567+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:03:02.626+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:03:02.631+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:03:03.101+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:03:03.101+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:04:03.163+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:04:03.167+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:04:03.654+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:04:03.654+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:05:03.709+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:05:03.714+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:05:04.207+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:05:04.207+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:06:04.266+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:06:04.271+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:06:04.746+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:06:04.747+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:07:04.798+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:07:04.803+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:07:05.295+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:07:05.295+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:08:05.354+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:08:05.359+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:08:05.882+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:08:05.882+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:09:05.942+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:09:05.947+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:09:06.416+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:09:06.417+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:10:06.474+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:10:06.479+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:10:06.964+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:10:06.964+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:11:07.022+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:11:07.027+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:11:08.272+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:11:08.273+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:12:08.330+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:12:08.335+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:12:08.834+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:12:08.834+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:13:08.842+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:13:08.847+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:13:09.335+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:13:09.335+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:14:09.396+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:14:09.401+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:14:09.928+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:14:09.928+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:15:09.985+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:15:09.990+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:15:10.475+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:15:10.475+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:16:10.534+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:16:10.540+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:16:11.043+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:16:11.043+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:17:11.105+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:17:11.110+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:17:11.588+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:17:11.588+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:18:11.646+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:18:11.651+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:18:12.140+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:18:12.140+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:19:12.202+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:19:12.207+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:19:12.684+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:19:12.684+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:20:12.742+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:20:12.747+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:20:13.221+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:20:13.221+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:21:13.284+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:21:13.290+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:21:13.764+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:21:13.764+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:22:13.824+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:22:13.829+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:22:14.315+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:22:14.315+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:23:14.374+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:23:14.379+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:23:14.856+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:23:14.857+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:24:14.914+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:24:14.918+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:24:15.402+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:24:15.402+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:25:15.461+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:25:15.466+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:25:15.971+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:25:15.971+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:26:16.033+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:26:16.037+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:26:16.502+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:26:16.502+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:27:16.561+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:27:16.565+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:27:17.041+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:27:17.041+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:28:17.102+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:28:17.107+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:28:17.579+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:28:17.579+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:29:17.638+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:29:17.643+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:29:18.191+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:29:18.192+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:30:18.250+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:30:18.255+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:30:18.738+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:30:18.738+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:31:18.798+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:31:18.803+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:31:19.275+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:31:19.275+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:32:19.336+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:32:19.341+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:32:19.814+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:32:19.814+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:33:19.866+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:33:19.870+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:33:21.170+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:33:21.170+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:34:21.231+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:34:21.235+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:34:21.725+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:34:21.725+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:35:21.786+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:35:21.791+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:35:22.276+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:35:22.277+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:36:22.337+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:36:22.342+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:36:22.820+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:36:22.820+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:37:22.851+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:37:22.857+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:37:24.087+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:37:24.087+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:38:24.146+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:38:24.151+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:38:24.622+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:38:24.623+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:39:24.682+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:39:24.687+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:39:25.161+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:39:25.162+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:40:25.213+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:40:25.218+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:40:25.721+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:40:25.721+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:41:25.782+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:41:25.787+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:41:26.256+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:41:26.257+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:42:26.318+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:42:26.323+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:42:26.796+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:42:26.796+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:43:26.854+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:43:26.858+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:43:27.349+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:43:27.349+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:44:27.398+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:44:27.402+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:44:27.871+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:44:27.871+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:45:27.930+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:45:27.935+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:45:28.408+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:45:28.408+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:46:28.466+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:46:28.471+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:46:28.965+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:46:28.965+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:47:29.026+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:47:29.030+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:47:29.510+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:47:29.511+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:48:29.570+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:48:29.575+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:48:30.860+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:48:30.860+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:49:30.918+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:49:30.923+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:49:31.411+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:49:31.411+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:50:31.473+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:50:31.480+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:50:32.760+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:50:32.760+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:51:32.818+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:51:32.823+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:51:33.312+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:51:33.313+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:52:33.370+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:52:33.375+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:52:33.849+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:52:33.850+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:53:33.910+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:53:33.915+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:53:34.401+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:53:34.401+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:54:34.463+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:54:34.468+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:54:34.945+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:54:34.946+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:55:35.006+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:55:35.013+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:55:35.530+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:55:35.530+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:56:35.590+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:56:35.595+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:56:36.077+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:56:36.077+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:57:36.138+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:57:36.143+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:57:37.444+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:57:37.444+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:58:37.505+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:58:37.511+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:58:37.989+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:58:37.989+0000] {http.py:171} ERROR - Not Found
[2023-05-15T03:59:38.002+0000] {http.py:122} INFO - Poking: https://randomuser.me/
[2023-05-15T03:59:38.008+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2023-05-15T03:59:38.506+0000] {http.py:170} ERROR - HTTP error: Not Found
[2023-05-15T03:59:38.507+0000] {http.py:171} ERROR - Not Found
[2023-05-15T04:00:18.790+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-05-15T04:00:23.930+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3059, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3137, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2858, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2976, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
